[package]
name = "blitz"
version = "0.1.0"
authors = ["toshihidefujii"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#edition = "2018"
[dependencies]
generic-array = "0.14.4"
num_cpus = "1.13.0"
rsys = "0.1.0"
page_size = "0.5.0"
rand = "0.8.5"

[workspace]
members = [
  "src/codegen",
]

[workspace.dependencies]
codegen = { path = "src/codegen"}