[package]
name = "blitz"
version = "0.1.0"
authors = ["toshihidefujii"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#edition = "2018"
[dependencies]
rlimit = "0.5.4"