#![allow(dead_code)]

// Defines the XRay profile class representing the latency profile
// generated by XRay's profiling mode.

pub fn load_profile() {}
pub fn merge_profiles_by_thread() {}
pub fn merge_profiles_by_stack() {}
pub fn profile_from_trace() {}

struct Data {}
struct Block {}
struct TrieNode {}

// Profile instances are thread-compatible.
struct Profile {}
impl Profile {
  pub fn new() {}
  pub fn expand_path() {}
  pub fn intern_path() {}
  pub fn add_block() {}
  pub fn swap() {}
  pub fn empty() {}
}