#![allow(dead_code)]

// Defines the XRay trace class representing records in an 
// xray trace file.

use super::xray_record::{XRayFileHeader, XRayRecord};

// A Trace object represents the records that have been loaded
// from XRay log files generated by instrumented binaries.
// We encapsulate the logic of reading the traces in factory functions
// that populate the Trace object appropriately.
struct Trace {
  file_header: XRayFileHeader,
  records: Vec<XRayRecord>
}

impl Trace {
  pub fn new() {}

  // Provides access to the loaded XRay trace file header.
  pub fn get_file_header(&self) -> &XRayFileHeader {
    &self.file_header
  }

  pub fn empty(&self) -> bool {
    self.records.is_empty()
  }

  pub fn size(&self) -> usize {
    self.records.len()
  }
}

pub fn load_trace_file() {}
pub fn load_trace() {}